# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('claimed_date', models.DateTimeField(blank=True, null=True, verbose_name='Used Date')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('voucher', models.CharField(choices=[('t-shirt', b'T-Shirt')], max_length=50)),
                ('voucher_info', jsonfield.fields.JSONField(blank=True, null=True)),
                ('token', models.CharField(db_index=True, max_length=50, unique=True)),
                ('human_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('last_edit_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Last Editor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
